services:
  ai:
    build:
      context: .
      dockerfile: ./apps/ai/Dockerfile
      target: development
    command: yarn start:dev ai
    env_file:
      - ./apps/ai/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/Users/brian/Documents/programming/hackathon/med/api-server
    depends_on:
      - weaviate
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      target: development
    command: yarn start
    ports:
      - '3000:3000'
    volumes:
      - .:/Users/brian/Documents/programming/hackathon/med/api-server
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.21.3
    ports:
      - 8080:8080
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
volumes:
  weaviate_data:
    driver: local
