# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: ['main']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

        with:
          node-version: ${{ matrix.node_version }}
          cache: 'yarn'
          cache-dependency-path: |
            yarn.lock

      - run: yarn install

      - name: create env file
        env:
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          WEAVIATE_URL: ${{ secrets.WEAVIATE_URL }}
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
        run: |
          touch .env
          echo MYSQL_ROOT_PASSWORD="$MYSQL_PASSWORD" >> .env
          echo MYSQL_DATABASE="$MYSQL_DB" >> .env
          echo MYSQL_DOCKER_IMAGE=mysql >> .env

          touch ./fastapi/.env
          echo COHERE_API_KEY="$COHERE_API_KEY" >> ./fastapi/.env

          touch ./apps/ai/.env
          echo HTTP_PORT=3001 >> ./apps/ai/.env
          echo WEAVIATE_URL="$WEAVIATE_URL" >> ./apps/ai/.env
          echo WEAVIATE_SCHEME=http >> ./apps/ai/.env

          echo COHERE_API_KEY="$COHERE_API_KEY" >> ./apps/ai/.env
          echo OPENAI_API_KEY="$OPENAI_API_KEY" >> ./apps/ai/.env
          echo SERPAPI_API_KEY="$SERPAPI_API_KEY" >> ./apps/ai/.env

      - name: rsync deployments
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: '-rltgoDzvO --delete'
          REMOTE_HOST: ${{ secrets.SSH_IP_ADDRESS }}
          REMOTE_USER: root
          TARGET: /root/api-server
